version: '3.1'
services:
  php-fpm:
    image: kazhuyo/zk-phpfpm:latest
    container_name: php-fpm
    restart: always
    env_file:
      - ./env/stage.env
    ports:
      - 9000:9000
    tmpfs: /var/cache
    tty: true
    volumes:
       - /local/path/to/approot:/usr/share/nginx/html
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
