version: '3.1'
services:
  nginx:
    image: kazhuyo/zk-nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    tty: true
    tmpfs:
      - /var/cache
    volumes:
      - db_data:/app
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
    env_file:
      - ./env/phpfpm.env
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: wordpress
    tty: true
    volumes:
       - db_data:/var/lib/mysql
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
  php-fpm:
    image: kazhuyo/zk-phpfpm
    container_name: php-fpm
    restart: always
    depends_on:
      - mariadb
    env_file:
      - ./env/phpfpm.env
    ports:
      - 9001:9000
    tmpfs:
      - /var/cache
    tty: true
    volumes:
       - db_data:/app
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
  redis:
    image: redis
    container_name: redis
    restart: always
volumes:
  db_data:
